### ISSUE TITLE
Issues in Nightly

### ISSUE THREAD

**Issue by chinaar** [gowong/tabtrekker#50]
Recently, Tabtrekker has stopped showing as the New Tab Page in nightly x64 as of version 20150629. This is likely to do with https://bugzilla.mozilla.org/show_bug.cgi?id=1118285 where the pref for setting the new tab page was removed and an API hook was added in its place. It still functions correctly as the home page.

Cheers.

**Comment by gowong** [comment]
Thanks for reporting this! I'll take a look as soon as I can.
