### ISSUE TITLE
TabTrekker, as homepage, doesn't load at startup

### ISSUE THREAD

**Issue by sojusnik** [gowong/tabtrekker#58]
Hey!

When TabTrekker (1.1.6 - the official version from [Mozilla](https://addons.mozilla.org/de/firefox/addon/tabtrekker/)) is set as the homepage of Firefox (v41.0.2), then upon startup TabTrekker seems to load the picture only after manually refreshing the page, as seen in this [video](https://mega.nz/#!j0ZTnCCT!saDDb4seEif-HJ97nVK3agHFfHQc5fpkLq0Cq97Si7M).

Best wishes!

**Comment by gowong** [comment]
Thanks for reporting this! I've found a pretty simple fix. Unfortunately, I'll need to wait some time before I can release it because I'm currently stuck waiting in the addon review process.
