### ISSUE TITLE
Time when location changes

### ISSUE THREAD

**Issue by sojusnik** [gowong/tabtrekker#60]
Hi!

Currently (v. 1.1.8), the location changes somewhere near midday, but it would be more natural to change the location some hours after midnight, so that in the morning a new location is present. Ideally the time when the location changes should be manually adjustable in the settings.

Best wishes!

**Comment by gowong** [comment]
The location updates whenever you open a new tab and it has been 24 hours since the location last updated. They don't actually change in the background.
