### ISSUE TITLE
Launching with about:newtab

### ISSUE THREAD

**Issue by sojusnik** [gowong/tabtrekker#77]
Launching TabTrekker with "about:newtab" instead of the current cryptic "resource://jid1-aahxeyitr16k5q-at-jetpack/tabtrekker/data/tabtrekker.html" (that also changes after every update) would make the binding to a certain keyword in Firefox much easier. The [Google Art Project](https://addons.mozilla.org/de/firefox/addon/art-project/) already does it that way. A double-click on the picture also summons the "recently visited" cites, that could be implented in TabTrekker too.

**Comment by gowong** [comment]
This sounds like it's only a cosmetic enhancement for the URL. Is that correct?

The current URL actually never changes since it uses the addon's id.

**Comment by sojusnik** [comment]
Yes and the additional ability to quickly see the most visited sites.

Regarding the ID: Then my impression was wrong :)

Gordon Wong <notifications@github.com> schrieb am Do., 7. Jän. 2016 16:38:

**Comment by gowong** [comment]
I see, is it hard to use the existing dropdown button?

**Comment by sojusnik** [comment]
Ah, missed that one :)
Thx

Gordon Wong <notifications@github.com> schrieb am Fr., 8. Jan. 2016 um
16:59 Uhr:

**Comment by gowong** [comment]
No worries, I'm going to close this since there isn't too much benefit with changing to the about:newtab URL. The current URL is already being hidden after opening a new tab.
