### ISSUE TITLE
Does not work on Firefox Developer edition

### ISSUE THREAD

**Issue by nemanjan00** [gowong/tabtrekker#78]
Version: 46.0a2 (2016-01-28)
Screenshot: 
![Screenshot](http://i.imgur.com/HXjpz4S.png)

**Comment by gowong** [comment]
Thanks for reporting. I haven't gotten a chance to test on Firefox 46 yet but I'll take a look soon

**Comment by gowong** [comment]
@nemanjan00 I just tested on Firefox developer edition 46.0a2 (2016-01-28) and it's working fine for me. Can you try reinstalling the addon?

**Comment by nemanjan00** [comment]
I just did. I use same profile for firefox stable and developer edition. In stable version, it works as expected but in developer edition, url of page is about:newtab instead of resources://... so all relative links on page are dead...

**Comment by gowong** [comment]
Okay, I was able to reproduce it now after trying on a different machine. Not sure why it wasn't seeing it the first time I tested it. I'll take a closer look soon.

**Comment by gowong** [comment]
I've pushed several commits that fixed the issue, but I'm going to wait a bit before releasing a new version. There's been a lot of instability around the new tab functionality in Firefox lately.

**Comment by nemanjan00** [comment]
I ca't build new version... 
```bash
╭─nemanjan00@nemanjan00-laptop  ~/tabtrekker/tabtrekker-develop/addon  
╰─$ python2 ../addon-sdk-1.17/bin/cfx xpi                                                                                                                                                   1 ↵
Warning: missing module: ./secrets
Warning: missing module: ./secrets
Warning: missing module: ./secrets
Warning: missing module: resource:///modules/NewTabURL.jsm
Warning: missing module: resource:///modules/NewTabURL.jsm
Exporting extension to tabtrekker.xpi.
```
And when I install it, I get just blank newtab... (I also had to disable signature requirement to install it)

**Comment by gowong** [comment]
The secrets file is required but isn't included in the codebase because it contains private API keys. Disabling the signature requirement is expected because the built xpi isn't signed by Mozilla.

I'll try to release a new version soon.
