### ISSUE TITLE
Parse getNextImageSet service not changing location

### ISSUE THREAD

**Issue by calvellido** [gowong/tabtrekker#80]
As someone noticed on the [Firefox addons page](https://addons.mozilla.org/en-US/firefox/addon/tabtrekker/reviews/778786/) TabTrekker is not shifting location on day changes.

After giving a look on the code I checked that `getNextImageSet` Parse service ([https://api.parse.com/1/functions/getNextImageSet](https://api.parse.com/1/functions/getNextImageSet)) is always answering with the same location: Hallstatt. This only happens with Parse production credentials, if you change to dev credentials the response changes.

**Comment by gowong** [comment]
I just tested this by forcing my TabTrekker instance to do a location update and the location definitely changed.

What query params did you include in the request? If you don't include any, it will always return the first location.

**Comment by calvellido** [comment]
Sorry, I have misunderstood the service behaviour, I've checked it again including a properly parsed object in the petition and the service is working correctly.

Anyway, as long as I'm using it, TabTrekker is always showing me Hallstatt. To be sure, I have uninstalled it, removed all preferences and reinstalled to check it again during the next few days.

As it refers to another question, I'm gonna close this issue and open a new one in case I continue encountering this problem, if you don't mind. I use Firefox with a privacy configuration where the history gets cleaned when Firefox closes (but still keeping “site preferences”), could that be a reason for this?

**Comment by gowong** [comment]
That might be affecting it, but I'm not completely sure. TabTrekker stores some data in Firefox's preferences. If you open up `about:config` and search for preferences starting with `extensions.jid1-AahxeYITR16k5Q@jetpack`, you should see that most of them have been modified and are in bold.

Maybe you can post a screenshot of what those preferences look like for you?

**Comment by calvellido** [comment]
Sure, here it goes:

![about_config](https://cloud.githubusercontent.com/assets/7753447/13047626/b0cd244e-d3e0-11e5-9fc6-cb45dbdabd2d.png)

And extracted through reading the `prefs.js` file:

```
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.homepage_enabled", true);
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.images", "[{\"imageUrl\":\"http://tabtrekker.parseapp.com/images/hallstatt/0.jpg\",\"infoUrl\":\"https://www.flickr.com/photos/adwriter/8598253153\",\"fileUri\":\"file:///home/jvalencia/.mozilla/firefox/23s3pp0r.default/tabtrekker/images/0/0.jpg\",\"resourceUri\":\"resource://tabtrekker_image_0_0\"},{\"imageUrl\":\"http://tabtrekker.parseapp.com/images/hallstatt/1.jpg\",\"infoUrl\":\"https://www.flickr.com/photos/jason_selby/6299680941\",\"fileUri\":\"file:///home/jvalencia/.mozilla/firefox/23s3pp0r.default/tabtrekker/images/0/1.jpg\",\"resourceUri\":\"resource://tabtrekker_image_0_1\"},{\"imageUrl\":\"http://tabtrekker.parseapp.com/images/hallstatt/2.jpg\",\"infoUrl\":\"https://www.flickr.com/photos/-igby-/3417992135\",\"fileUri\":\"file:///home/jvalencia/.mozilla/firefox/23s3pp0r.default/tabtrekker/images/0/2.jpg\",\"resourceUri\":\"resource://tabtrekker_image_0_2\"},{\"imageUrl\":\"http://tabtrekker.parseapp.com/images/hallstatt/3.jpg\",\"infoUrl\":\"https://www.flickr.com/photos/kainet/6944343289\",\"fileUri\":\"file:///home/jvalencia/.mozilla/firefox/23s3pp0r.default/tabtrekker/images/0/3.jpg\",\"resourceUri\":\"resource://tabtrekker_image_0_3\"},{\"imageUrl\":\"http://tabtrekker.parseapp.com/images/hallstatt/4.jpg\",\"infoUrl\":\"https://www.flickr.com/photos/diueine/402582427\",\"fileUri\":\"file:///home/jvalencia/.mozilla/firefox/23s3pp0r.default/tabtrekker/images/0/4.jpg\",\"resourceUri\":\"resource://tabtrekker_image_0_4\"},{\"imageUrl\":\"http://tabtrekker.parseapp.com/images/hallstatt/5.jpg\",\"infoUrl\":\"https://www.flickr.com/photos/adwriter/12160194766\",\"fileUri\":\"file:///home/jvalencia/.mozilla/firefox/23s3pp0r.default/tabtrekker/images/0/5.jpg\",\"resourceUri\":\"resource://tabtrekker_image_0_5\"},{\"imageUrl\":\"http://tabtrekker.parseapp.com/images/hallstatt/6.jpg\",\"infoUrl\":\"https://www.flickr.com/photos/aktugan/10992406363\",\"fileUri\":\"file:///home/jvalencia/.mozilla/firefox/23s3pp0r.default/tabtrekker/images/0/6.jpg\",\"resourceUri\":\"resource://tabtrekker_image_0_6\"},{\"imageUrl\":\"http://tabtrekker.parseapp.com/images/hallstatt/7.jpg\",\"infoUrl\":\"https://www.flickr.com/photos/aktugan/10992357054\",\"fileUri\":\"file:///home/jvalencia/.mozilla/firefox/23s3pp0r.default/tabtrekker/images/0/7.jpg\",\"resourceUri\":\"resource://tabtrekker_image_0_7\"},{\"imageUrl\":\"http://tabtrekker.parseapp.com/images/hallstatt/8.jpg\",\"infoUrl\":\"https://www.flickr.com/photos/jason_selby/6344737032\",\"fileUri\":\"file:///home/jvalencia/.mozilla/firefox/23s3pp0r.default/tabtrekker/images/0/8.jpg\",\"resourceUri\":\"resource://tabtrekker_image_0_8\"},{\"imageUrl\":\"http://tabtrekker.parseapp.com/images/hallstatt/9.jpg\",\"infoUrl\":\"https://www.flickr.com/photos/aktugan/10992428773\",\"fileUri\":\"file:///home/jvalencia/.mozilla/firefox/23s3pp0r.default/tabtrekker/images/0/9.jpg\",\"resourceUri\":\"resource://tabtrekker_image_0_9\"}]");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.images_chosen_id", 0);
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.images_fallback_id", 3);
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.images_image_set", "{\"id\":0,\"infoUrl\":\"http://en.wikipedia.org/wiki/Hallstatt\",\"name\":\"Hallstatt, Austria\",\"startingImageId\":0,\"numImages\":10}");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.images_lastchosen", "1455526700580");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.images_lastupdated", "1455526700580");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.location", "Seville, Spain");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.location_geocoded_name", "Sevilla");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.location_geolocation_latitude", "37.3890924");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.location_geolocation_longitude", "-5.9844589");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.parse_image_set_id", 0);
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.parse_viewed_image_set_ids", "[0]");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.sdk.baseURI", "resource://jid1-aahxeyitr16k5q-at-jetpack/");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.sdk.domain", "jid1-aahxeyitr16k5q-at-jetpack");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.sdk.load.reason", "install");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.sdk.rootURI", "jar:file:///home/jvalencia/.mozilla/firefox/23s3pp0r.default/extensions/jid1-AahxeYITR16k5Q@jetpack.xpi!/");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.sdk.version", "1.2.1");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.search_engine", "duckduckgo");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.show_menu", "hover");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.show_search", "hover");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.temperature_units", "C");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.time_format", "24hour");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.weather_conditions", "{\"description\":\"Soleado\",\"icon\":\"B\"}");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.weather_lastupdated", "1455526742780");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.weather_location_name", "Sevilla");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.weather_temperature", "10");
user_pref("extensions.jid1-AahxeYITR16k5Q@jetpack.weather_temperature_units", "°C");
```

**Comment by gowong** [comment]
Thanks for the screenshot, I don't see anything wrong with the preferences. We can try forcing the location to update and see if that works:
1. Open `about:config` and search for `extensions.jid1-AahxeYITR16k5Q@jetpack.images_lastupdated`
1. Right click the preference and click reset.
1. Open a new tab and you should see the loading screen. Wait for it to finish and see if the location changes.
1. If the location doesn't change, could you post your preferences again immediately after following the above steps?

**Comment by calvellido** [comment]
Hi again, by following those steps the location did correctly change. Presumably the location should automatically change tomorrow, isn't it?  Then, I will wait for the next days to see what happens and report about it.

Thank you.

**Comment by gowong** [comment]
Yes it should change automatically, it's strange that it wasn't working before.
Please note that the location will only change after a full 24 hours. I'll close this for now, feel free to comment again if it's still not working.

**Comment by calvellido** [comment]
Hello, after the property reset now TabTrekker has been changing the location every 24 hours correctly. Great pictures btw, I'm already loving this extension. 

I'm not sure if the first time was a problem with my Firefox History configuration, but now it works flawlessly. 

Thank you very much for the support.
