### ISSUE TITLE
Suggestion: Make text more legible on light coloured backgrounds

### ISSUE THREAD

**Issue by lamga** [gowong/tabtrekker#84]
Issue:Text, especially the image caption and weather location text, are not very legible when a light coloured or white coloured background is used.
Suggestion: Apply a black or dark grey text-shadow to all text.

P.S. Keep it up!

**Comment by gowong** [comment]
Thanks for the feedback. There actually already is some shadow around the text and buttons if you hover over them. I had to make the shadow subtle otherwise it wouldn't look good.
